# Generated by Django 5.2.6 on 2025-10-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersiprunningmetric',
            name='user',
        ),
        migrations.RenameField(
            model_name='servicefeeslab',
            old_name='percentage',
            new_name='fee_percentage',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password_hash',
        ),
        migrations.RemoveField(
            model_name='servicefeeslab',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='servicefeeslab',
            name='max_sip_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicefeeslab',
            name='min_sip_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=100000, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SIPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bitcoin_price_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monthly_sip_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bitcoin_quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('service_fee_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserSIPRunningMetric',
        ),
    ]
