# Generated by Django 5.2.6 on 2025-10-01 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipapp', '0002_bitcoinpricehistory_remove_usersiprunningmetric_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinpricehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitcoinpricehistory',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='servicefeeslab',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicefeeslab',
            name='max_sip_amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='servicefeeslab',
            name='min_sip_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='bitcoin_price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='bitcoin_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='monthly_sip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='net_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='siptransaction',
            name='service_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user1', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='UserSIPRunningMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sipapp.user')),
            ],
        ),
    ]
